image: "node:12"

before_script:
  - yarn install

build:
  stage: build
  script:
    - yarn run build
  cache:
    policy: push
    paths:
      - node_modules/
      - .yarn
  artifacts:
    paths:
      - dist/

staging:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=rosiebot-dev --api-key=$HEROKU_API_KEY
  only:
    - staging

deploy_prod:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - npx semantic-release
    - dpl --provider=heroku --app=rosiebot-prod --api-key=$HEROKU_API_KEY
  only:
    - master
  when: manual
